extract_params:
  window_duration_days: 30
  start_date: '2013/01/01'
  end_date: '2023/11/01'

top_k_params:
  top_k: 3 # will also be used for ensemble_strategy
  retrieval_strategy: "similarity" #alternatives: "similarity", "max_marginal_relevance", "ensemble_retrieval"
  advanced_dense_retriever: "similarity" #alternative "mmr" # is only relevant when ensemble_retrieval or multi_query_retrieval are selected as retrieval strategy
  mq_include_original: False #boolean indicating if by multiquery retrieval the original query should be included

modelling_params:
  spell_checker: True
  abstract_only: True
  # prompt_template: '''
  #   You are an AI assistant that answers questions using as few words as possible and only based on the following context:
  #   {context}
  #   Question: {question}
  # '''

  prompt_template: '''
    Be as short as possible in your answer. As an AI assistant, answer the question accurately, precisely and concisely. Use the following context: 
    {context}
    Question: {question}
  '''

  temperature: 0
  max_tokens: 1000
  n_ctx: 2048
  top_p: 1
  n_gpu_layers: 40
  n_batch: 512
  verbose: False
  metadata_strategy: "parser" # alternative: "llm_detection"
