extract_params:
  window_duration_days: 30
  start_date: '2013/01/01'
  end_date: '2023/11/01'

top_k_params:
  top_k: 3
  retrieval_strategy: "similarity_search" #alternative: max_marginal_relevance
